---
# tasks file for setting up a devops workstation
  - name: Add SubmlimeText repo key (rpm)
    rpm_key: 
      state: present
      key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    when: ansible_facts['os_family'] == "Suse"

  - name: Add SublimeText repo key (apt)
    apt_key:
      state: present
      url: https://download.sublimetext.com/sublimehq-pub.gpg
    when: ansible_facts['os_family'] == "Debian"

  - name: Enable SublimeText repo (Debian)
    apt_repository:
      repo: "deb https://download.sublimetext.com/ apt/stable/"
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Enable stable SublimeText repo (OpenSuse)
    zypper_repository:
      repo: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
      name: sublime-text-stable-repo
      state: present
      runrefresh: yes
    when: ansible_facts['os_family'] == "Suse"

  - name: Install devops tools
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - ansible
      - tmux
      - zsh
      - docker
      - shellcheck
      - sublime-text